
import __ASTRO_IMAGE_IMPORT_1s2MGs from "../../assets/images/calle.webp?astroContentImageFlag=&importer=src%2Fcontent%2Farticulos%2Fhistoria-avenida-chile.md";
import __ASTRO_IMAGE_IMPORT_R0RiH from "../../assets/images/fachada.webp?astroContentImageFlag=&importer=src%2Fcontent%2Farticulos%2Farquitectura-moderna-parkway.md";
import __ASTRO_IMAGE_IMPORT_Z1IvXFI from "../../assets/images/fachada.webp?astroContentImageFlag=&importer=src%2Fcontent%2Feventos%2Frecorrido-patrimonial.md";
import __ASTRO_IMAGE_IMPORT_1oMoKk from "../../assets/images/fachada.webp?astroContentImageFlag=&importer=src%2Fcontent%2Flugares%2Ffachadas-avenida-chile.md";
import __ASTRO_IMAGE_IMPORT_hKP3G from "../../assets/images/oliveto.webp?astroContentImageFlag=&importer=src%2Fcontent%2Frestaurantes%2Foliveto.md";
import __ASTRO_IMAGE_IMPORT_1LGosq from "../../assets/images/oliveto2.webp?astroContentImageFlag=&importer=src%2Fcontent%2Farticulos%2Fguia-cafes-especialidad.md";
import __ASTRO_IMAGE_IMPORT_Z1nWQDr from "../../assets/images/parque-atardecer.webp?astroContentImageFlag=&importer=src%2Fcontent%2Feventos%2Fvino-al-parkway-2025.md";
import __ASTRO_IMAGE_IMPORT_byQcS from "../../assets/images/parque.webp?astroContentImageFlag=&importer=src%2Fcontent%2Feventos%2Fmercado-artesanal.md";
import __ASTRO_IMAGE_IMPORT_MuMQ4 from "../../assets/images/parque.webp?astroContentImageFlag=&importer=src%2Fcontent%2Flugares%2Falameda-el-parkway.md";
import __ASTRO_IMAGE_IMPORT_Z1E7gQk from "../../assets/images/parque2.webp?astroContentImageFlag=&importer=src%2Fcontent%2Flugares%2Fparque-la-soledad.md";
import __ASTRO_IMAGE_IMPORT_ZnivAf from "../../assets/images/restaurante.webp?astroContentImageFlag=&importer=src%2Fcontent%2Frestaurantes%2Fcafe-zaguan.md";
import __ASTRO_IMAGE_IMPORT_Z2gzWF2 from "../../assets/images/restaurante2.webp?astroContentImageFlag=&importer=src%2Fcontent%2Frestaurantes%2Fterracota.md";
export default new Map([["../../assets/images/calle.webp?astroContentImageFlag=&importer=src%2Fcontent%2Farticulos%2Fhistoria-avenida-chile.md", __ASTRO_IMAGE_IMPORT_1s2MGs], ["../../assets/images/fachada.webp?astroContentImageFlag=&importer=src%2Fcontent%2Farticulos%2Farquitectura-moderna-parkway.md", __ASTRO_IMAGE_IMPORT_R0RiH], ["../../assets/images/fachada.webp?astroContentImageFlag=&importer=src%2Fcontent%2Feventos%2Frecorrido-patrimonial.md", __ASTRO_IMAGE_IMPORT_Z1IvXFI], ["../../assets/images/fachada.webp?astroContentImageFlag=&importer=src%2Fcontent%2Flugares%2Ffachadas-avenida-chile.md", __ASTRO_IMAGE_IMPORT_1oMoKk], ["../../assets/images/oliveto.webp?astroContentImageFlag=&importer=src%2Fcontent%2Frestaurantes%2Foliveto.md", __ASTRO_IMAGE_IMPORT_hKP3G], ["../../assets/images/oliveto2.webp?astroContentImageFlag=&importer=src%2Fcontent%2Farticulos%2Fguia-cafes-especialidad.md", __ASTRO_IMAGE_IMPORT_1LGosq], ["../../assets/images/parque-atardecer.webp?astroContentImageFlag=&importer=src%2Fcontent%2Feventos%2Fvino-al-parkway-2025.md", __ASTRO_IMAGE_IMPORT_Z1nWQDr], ["../../assets/images/parque.webp?astroContentImageFlag=&importer=src%2Fcontent%2Feventos%2Fmercado-artesanal.md", __ASTRO_IMAGE_IMPORT_byQcS], ["../../assets/images/parque.webp?astroContentImageFlag=&importer=src%2Fcontent%2Flugares%2Falameda-el-parkway.md", __ASTRO_IMAGE_IMPORT_MuMQ4], ["../../assets/images/parque2.webp?astroContentImageFlag=&importer=src%2Fcontent%2Flugares%2Fparque-la-soledad.md", __ASTRO_IMAGE_IMPORT_Z1E7gQk], ["../../assets/images/restaurante.webp?astroContentImageFlag=&importer=src%2Fcontent%2Frestaurantes%2Fcafe-zaguan.md", __ASTRO_IMAGE_IMPORT_ZnivAf], ["../../assets/images/restaurante2.webp?astroContentImageFlag=&importer=src%2Fcontent%2Frestaurantes%2Fterracota.md", __ASTRO_IMAGE_IMPORT_Z2gzWF2]]);
		